// Generate the Chromium shell's binding to CEF's C API (D82): `src/Shenora.Chromium/Interop/Generated/`.
//
//   node devtools/dev.mjs cef-binding          regenerate from the pin in src/Shenora.Chromium/cef.json
//
// The binding is ClangSharp's P/Invoke generator run over CEF's own C headers, once per OS, for ONE
// Stable API version. CEF's API versioning is why that is enough: a client built for a Stable version
// runs on every past and future CEF binary that still supports it, so a Chromium security update is a
// binary swap, and this runs only when the pin moves to a new API version.
//
// Where the headers come from: include/capi is GENERATED by CEF's build, so it exists only inside a
// binary distribution (the Windows one, downloaded and SHA-1-checked against CEF's own index). The
// other OSes' internal headers are in CEF's git repo at the build's commit.
//
// Three things this has to get right, each found by diffing the three outputs:
// - `-c types=` defaults to the HOST. Without `types=unix`, generating for Linux on Windows maps C
//   `long` to 32 bits, and Linux's `unsigned long` window handle came out as `uint`.
// - Stdcall (Windows) and Cdecl (POSIX) are ONE convention on x64 and ARM64, so both are normalised to
//   the platform default. MSVC types an enum as int where clang on POSIX says unsigned int. Same 4 bytes,
//   so int is kept, except for an enum holding a value at or above 2^31, which stays per OS.
// - Every POSIX export carries visibility("default"), which ClangSharp warns about once per export and
//   counts in its exit code. Exactly those warnings are accepted. Anything else fails the run.
//
// Build per OS: the Common files reference per-OS types by name (a browser returns a per-OS host), so
// a build compiles Common + ONE OS folder, chosen by the project from the runtime identifier.
import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const project = path.join(repo, 'src', 'Shenora.Chromium');
const pin = JSON.parse(fs.readFileSync(path.join(project, 'cef.json'), 'utf8'));
const CLANGSHARP = '21.1.8.4';
const cache = path.join(repo, 'devtools', '_cache', 'cef', pin.cef);
const tools = path.join(repo, 'devtools', '_tools', 'clangsharp', CLANGSHARP);
const OSES = { Windows: 'x86_64-pc-windows-msvc', MacOS: 'x86_64-apple-darwin', Linux: 'x86_64-unknown-linux-gnu' };

/** Thrown, never `process.exit()`: an exit with a fetch in flight aborts Node and REPLACES the exit code. */
class CefBindingError extends Error {}
function fail(message) {
  throw new CefBindingError(message);
}

const commit = /\+g([0-9a-f]+)\+/.exec(pin.cef)?.[1];

function run(cmd, args, options = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024, ...options });
  if (r.error) fail(`${cmd} could not start: ${r.error.message}`);
  return r;
}

/** CEF's own index names the file and its SHA-1; a download that does not match it is never used. */
async function distribution() {
  const marker = path.join(cache, 'extracted.sha1');
  const root = path.join(cache, 'dist');
  if (fs.existsSync(marker)) return root;

  const index = await (await fetch('https://cef-builds.spotifycdn.com/index.json')).json();
  const build = index.windows64?.versions?.find((v) => v.cef_version === pin.cef);
  if (!build) fail(`CEF's index has no windows64 build ${pin.cef}.`);
  const file = build.files.find((f) => f.type === 'minimal');
  fs.mkdirSync(cache, { recursive: true });
  const archive = path.join(cache, file.name);

  if (!fs.existsSync(archive)) {
    console.log(`cef-binding: downloading ${file.name} (${(file.size / 1048576).toFixed(0)} MB)`);
    const response = await fetch(`https://cef-builds.spotifycdn.com/${encodeURIComponent(file.name)}`);
    if (!response.ok) fail(`download failed: HTTP ${response.status}`);
    fs.writeFileSync(archive + '.part', Buffer.from(await response.arrayBuffer()));
    fs.renameSync(archive + '.part', archive);
  }
  const sha1 = crypto.createHash('sha1').update(fs.readFileSync(archive)).digest('hex');
  if (sha1 !== file.sha1) {
    fs.rmSync(archive, { force: true });
    fail(`SHA-1 mismatch for ${file.name}: got ${sha1}, the index says ${file.sha1}. The file was deleted.`);
  }

  console.log('cef-binding: extracting (the archive is bzip2, which is most of the time spent)');
  fs.rmSync(root, { recursive: true, force: true });
  fs.mkdirSync(root, { recursive: true });
  // RELATIVE paths from inside the cache: Git's GNU tar reads `D:\…` as a remote host named "D"
  // ("Cannot connect to D: resolve failed"), and Windows' own bsdtar accepts the relative form too.
  const tar = run('tar', ['-xjf', path.basename(archive), '-C', path.basename(root)], { cwd: cache });
  if (tar.status !== 0) fail(`tar failed: ${tar.stderr}`);
  const top = fs.readdirSync(root).find((d) => d.startsWith('cef_binary_'));
  if (!top) fail('the archive held no cef_binary_* folder.');
  fs.renameSync(path.join(root, top), path.join(root, 'cef'));
  fs.writeFileSync(marker, sha1);
  return root;
}

/** The distribution's include tree, plus the other OSes' internal headers from CEF's git at the commit. */
async function stagedIncludes(dist) {
  const stage = path.join(cache, 'stage');
  fs.rmSync(stage, { recursive: true, force: true });
  copyDir(path.join(dist, 'cef', 'include'), path.join(stage, 'include'));
  for (const name of ['cef_types_linux.h', 'cef_linux.h', 'cef_types_mac.h', 'cef_mac.h']) {
    const response = await fetch(`https://raw.githubusercontent.com/chromiumembedded/cef/${commit}/include/internal/${name}`);
    if (!response.ok) fail(`CEF's repo has no include/internal/${name} at ${commit} (HTTP ${response.status}).`);
    fs.writeFileSync(path.join(stage, 'include', 'internal', name), await response.text());
  }
  return stage;
}

/** Manual recursion: fs.cpSync crashes this machine's Node 24 (windows-dev-gotchas). */
function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, e.name), d = path.join(to, e.name);
    if (e.isDirectory()) copyDir(s, d); else fs.copyFileSync(s, d);
  }
}

/**
 * macOS and Linux: no C library is visible from here, so the handful of C headers CEF's C API
 * includes are stated with the LP64 target's real sizes. Nothing else may appear in a struct layout.
 */
function sysroot() {
  const dir = path.join(cache, 'sysroot');
  const files = {
    'stdint.h': 'typedef signed char int8_t; typedef short int16_t; typedef int int32_t; typedef long long int64_t;\n'
      + 'typedef unsigned char uint8_t; typedef unsigned short uint16_t; typedef unsigned int uint32_t; typedef unsigned long long uint64_t;\n'
      + 'typedef long intptr_t; typedef unsigned long uintptr_t;\n#define INT32_MAX 2147483647\n#define INT64_MAX 9223372036854775807LL\n#define UINT32_MAX 4294967295U\n',
    'stddef.h': 'typedef unsigned long size_t; typedef long ptrdiff_t; typedef int wchar_t;\n#define NULL ((void*)0)\n#define offsetof(t, m) __builtin_offsetof(t, m)\n',
    'uchar.h': 'typedef unsigned short char16_t; typedef unsigned int char32_t;\n',
    'time.h': 'typedef long time_t;\n',
    'limits.h': '#define INT_MAX 2147483647\n#define UINT_MAX 4294967295U\n#define LONG_MAX 9223372036854775807L\n',
    'sys/types.h': 'typedef int pid_t;\n',
    'unistd.h': '#include <sys/types.h>\n',
    'pthread.h': '#if defined(__APPLE__)\ntypedef struct _opaque_pthread_t* pthread_t;\n#else\ntypedef unsigned long pthread_t;\n#endif\n',
    'TargetConditionals.h': '#define TARGET_OS_MAC 1\n#define TARGET_OS_OSX 1\n#define TARGET_OS_IPHONE 0\n#define TARGET_OS_IOS 0\n',
  };
  for (const [name, text] of Object.entries(files)) {
    fs.mkdirSync(path.dirname(path.join(dir, name)), { recursive: true });
    fs.writeFileSync(path.join(dir, name), '#pragma once\n' + text);
  }
  return dir;
}

function clangSharp() {
  const exe = path.join(tools, '.store', 'clangsharppinvokegenerator', CLANGSHARP, 'clangsharppinvokegenerator.win-x64',
    CLANGSHARP, 'tools', 'any', 'win-x64', 'ClangSharpPInvokeGenerator.exe');
  if (fs.existsSync(exe)) return exe;
  const r = run('dotnet', ['tool', 'install', 'ClangSharpPInvokeGenerator', '--version', CLANGSHARP, '--tool-path', tools]);
  if (r.status !== 0) fail(`installing ClangSharp ${CLANGSHARP} failed: ${r.stdout}${r.stderr}`);
  // The install lays down a .cmd shim, which Node will not spawn without a shell: the real exe is used.
  if (!fs.existsSync(exe)) fail(`ClangSharp ${CLANGSHARP} installed, but not where expected: ${exe}`);
  return exe;
}

function generate(tool, stage, os, work) {
  const rel = (dir) => fs.readdirSync(path.join(stage, dir)).filter((f) => f.endsWith('.h')).map((f) => `${dir}/${f}`);
  const capi = [...rel('include/capi'), ...rel('include/capi/views')];
  const internal = rel('include/internal')
    .filter((f) => /cef_(types|string|time|thread_internal|logging_internal|trace_event_internal|dump_without_crashing_internal|export)/.test(f))
    .filter((f) => !f.endsWith('_wrappers.h'));
  const umbrella = path.join(work, 'cef_all.h');
  fs.writeFileSync(umbrella, [...capi, 'include/cef_api_hash.h'].map((f) => `#include "${f}"`).join('\n') + '\n');
  const header = path.join(work, 'header.txt');
  fs.writeFileSync(header, [
    '// <auto-generated>',
    `// Generated by \`node devtools/dev.mjs cef-binding\` from CEF ${pin.cef}'s C API headers at Stable API`,
    `// version ${pin.apiVersion}. Do not edit: regenerate. The headers are the Chromium Embedded Framework's,`,
    '// BSD-3-Clause, Copyright (c) Marshall A. Greenblatt; see THIRD-PARTY-NOTICES.md beside the project.',
    '// </auto-generated>',
    '#pragma warning disable CS8981, CS0649, CS0169',
    '',
  ].join('\n'));

  const out = path.join(work, os);
  fs.mkdirSync(out, { recursive: true });
  const windows = os === 'Windows';
  const args = [
    '--file', umbrella, '--language', 'c', '--include-directory', stage,
    '--define-macro', `CEF_API_VERSION=${pin.apiVersion}`,
    '--additional', `--target=${OSES[os]}`,
    ...(windows ? [] : ['--additional', '-ffreestanding', '--additional', '-nostdinc', '--additional', `-isystem${sysroot()}`]),
    '--namespace', 'Shenora.Chromium.Interop', '--method-class-name', 'Cef', '--library-path', 'libcef',
    '--output', out, '--header-file', header,
    '--config', 'codegen=latest', 'file=multi', `types=${windows ? 'windows' : 'unix'}`,
    '--generate', 'file-scoped-namespaces', '--generate', 'funcs-with-body=false', '--generate', 'helper-types',
    '--with-access-specifier', '*=Internal',
    // OS handle types CEF names only as pointers: integers, never a walk into the OS SDK. macOS's
    // pthread_t is `struct _opaque_pthread_t *`; Linux's is `unsigned long`, which is already nuint.
    ...{
      Windows: ['HWND__*=nint', 'HINSTANCE__*=nint', 'HICON__*=nint', 'HMENU__*=nint', 'HCURSOR__*=nint', 'tagMSG*=nint'],
      MacOS: ['_opaque_pthread_t*=nint'],
      Linux: [],
    }[os].flatMap((r) => ['--remap', r]),
    ...[...capi, ...internal, 'include/cef_api_hash.h'].flatMap((f) => ['--traverse', path.join(stage, f)]),
  ];
  const rsp = path.join(work, `${os}.rsp`);
  fs.writeFileSync(rsp, args.map((a) => (/\s/.test(a) ? `"${a}"` : a)).join('\n'));
  const r = run(tool, ['@' + rsp]);
  const log = (r.stdout ?? '') + (r.stderr ?? '');
  fs.writeFileSync(path.join(work, `${os}.log`), log);

  const visibility = (log.match(/Unsupported attribute: 'Visibility'/g) ?? []).length;
  // Case-INSENSITIVE: clang writes `file:line:col: error: …` while ClangSharp writes `Warning (Line …)`.
  // A case-sensitive filter let a sabotaged run fail on its exit code alone, naming no cause. The
  // closing "Skipping … due to one or more errors" is a summary, so the real error is named first.
  const other = log.split('\n').map((l) => l.trim())
    .filter((l) => /\b(warning|error)\b/i.test(l) && !/'Visibility'/.test(l) && !/^Skipping /.test(l));
  if (other.length > 0 || r.status !== (windows ? 0 : visibility))
    fail(`${os}: exit ${r.status}, ${visibility} visibility warning(s), ${other.length} other diagnostic(s). `
      + `First: ${other[0]?.trim() ?? '(none)'} — full log: ${path.join(work, `${os}.log`)}`);
  return out;
}

const exceedsInt = (text) => /\b(0x[89A-Fa-f][0-9A-Fa-f]{7}|[2-4]\d{9})U?\b/.test(text);
function normalise(text) {
  let t = text.replace(/unmanaged\[(Stdcall|Cdecl)\]/g, 'unmanaged').replace(/ __attribute__\(\(stdcall\)\)/g, '');
  if (!exceedsInt(t)) t = t.replace(/\[NativeTypeName\("unsigned int"\)\]\r?\n(\s*)internal enum (\w+) : uint/g, '$1internal enum $2');
  return t;
}

/** Files identical on every OS go to Common; the rest to one folder per OS. Only Generated/ is replaced. */
function writeBinding(outputs) {
  const target = path.join(project, 'Interop', 'Generated');
  fs.rmSync(target, { recursive: true, force: true });
  for (const d of ['Common', ...Object.keys(OSES)]) fs.mkdirSync(path.join(target, d), { recursive: true });

  const names = [...new Set(Object.values(outputs).flatMap((o) => Object.keys(o)))].sort();
  const perOs = [];
  for (const name of names) {
    const texts = Object.keys(OSES).map((os) => outputs[os][name]);
    if (texts.every((t) => t !== undefined && t === texts[0])) {
      fs.writeFileSync(path.join(target, 'Common', name), texts[0]);
      continue;
    }
    perOs.push(name);
    Object.keys(OSES).forEach((os, i) => {
      if (texts[i] !== undefined) fs.writeFileSync(path.join(target, os, name), texts[i]);
    });
  }

  fs.writeFileSync(path.join(project, 'Interop', 'CefApi.g.cs'), [
    '// <auto-generated>Written by `node devtools/dev.mjs cef-binding` from cef.json. Do not edit.</auto-generated>',
    'namespace Shenora.Chromium.Interop;',
    '',
    'internal static class CefApi',
    '{',
    '    /// <summary>The Stable API version the binding was generated for; <c>cef_api_hash</c> reports it first.</summary>',
    `    public const int Version = ${pin.apiVersion};`,
    '',
    '    /// <summary>The CEF build whose headers produced the binding.</summary>',
    `    public const string Build = "${pin.cef}";`,
    '}',
    '',
  ].join('\n'));
  console.log(`cef-binding: ${names.length} files — ${names.length - perOs.length} common, ${perOs.length} per OS (${perOs.join(', ')})`);
}

async function main() {
  if (!commit) fail(`cef.json's "cef" (${pin.cef}) carries no +g<commit>+ — copy it from CEF's index verbatim.`);
  const dist = await distribution();
  const stage = await stagedIncludes(dist);
  const tool = clangSharp();
  const work = path.join(cache, 'generated');
  fs.rmSync(work, { recursive: true, force: true });
  fs.mkdirSync(work, { recursive: true });

  const outputs = {};
  for (const os of Object.keys(OSES)) {
    const dir = generate(tool, stage, os, work);
    outputs[os] = Object.fromEntries(fs.readdirSync(dir).map((f) => [f, normalise(fs.readFileSync(path.join(dir, f), 'utf8'))]));
    console.log(`cef-binding: ${os} — ${Object.keys(outputs[os]).length} files`);
  }
  writeBinding(outputs);
}

try {
  await main();
} catch (error) {
  console.error(`cef-binding: ${error instanceof CefBindingError ? error.message : error.stack}`);
  process.exitCode = 1;
}
