// <auto-generated>Written by `node devtools/dev.mjs cef-binding` from cef.json. Do not edit.</auto-generated>
namespace Shenora.Chromium.Interop;

internal static class CefApi
{
    /// <summary>The Stable API version the binding was generated for; <c>cef_api_hash</c> reports it first.</summary>
    public const int Version = 15400;

    /// <summary>The CEF build whose headers produced the binding.</summary>
    public const string Build = "154.0.28+g564dd6c+chromium-154.0.8037.58";
}
