# shenora_launcher_startup_screen(<target> IMAGE <png> [WIDTH n] [HEIGHT n] [BACKGROUND "#RRGGBB"|"#AARRGGBB"]
#   [PROGRESS_BAR ON|OFF] [PROGRESS_COLOR "#..."] [CORNERS ROUNDED|SQUARE] [MONITOR CURSOR|PRIMARY] [TIMEOUT_SECONDS n])
#
# Compiles a startup screen's description and its PNG into <target>, a launcher built from template/main.cpp: the
# launcher stays one file. Sizes are in device-independent pixels and TIMEOUT_SECONDS a whole number; the PNG is fitted
# inside the box, aspect kept, and scaled for the monitor's DPI, so give it at about twice the box (a 960×600 PNG is
# typically 100–500 KB; its decode is on the screen's first frame, so a bigger one shows later). Values are not
# case-sensitive. A changed PNG re-runs CMake by itself. Without this call the launcher shows no screen.
function(shenora_launcher_startup_screen target)
  cmake_parse_arguments(S "" "IMAGE;WIDTH;HEIGHT;BACKGROUND;PROGRESS_BAR;PROGRESS_COLOR;CORNERS;MONITOR;TIMEOUT_SECONDS" "" ${ARGN})
  set(where "shenora_launcher_startup_screen(${target})")
  if(NOT S_IMAGE)
    message(FATAL_ERROR "${where}: IMAGE is required")
  endif()
  if(NOT EXISTS "${S_IMAGE}")
    message(FATAL_ERROR "${where}: no image at ${S_IMAGE}")
  endif()
  file(SIZE "${S_IMAGE}" image_size)
  if(image_size EQUAL 0)
    message(FATAL_ERROR "${where}: ${S_IMAGE} is empty")
  endif()
  foreach(pair "WIDTH;480" "HEIGHT;300" "BACKGROUND;#FF202020" "PROGRESS_BAR;OFF" "PROGRESS_COLOR;#FF3B82F6"
               "CORNERS;ROUNDED" "MONITOR;CURSOR" "TIMEOUT_SECONDS;20")
    list(GET pair 0 key)
    list(GET pair 1 value)
    if(NOT DEFINED S_${key})
      set(S_${key} "${value}")
    endif()
  endforeach()
  foreach(key WIDTH HEIGHT TIMEOUT_SECONDS)
    if(NOT S_${key} MATCHES "^[0-9]+$" OR S_${key} EQUAL 0)
      message(FATAL_ERROR "${where}: ${key} must be a positive whole number, not '${S_${key}}'")
    endif()
  endforeach()
  # "#RRGGBB" → 0xFFRRGGBB, "#AARRGGBB" → 0xAARRGGBB
  foreach(c BACKGROUND PROGRESS_COLOR)
    string(REGEX REPLACE "^#" "" hex "${S_${c}}")
    if(NOT hex MATCHES "^([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])([0-9A-Fa-f][0-9A-Fa-f])?$")
      message(FATAL_ERROR "${where}: ${c} must be #RRGGBB or #AARRGGBB, not '${S_${c}}'")
    endif()
    string(LENGTH "${hex}" len)
    if(len EQUAL 6)
      set(hex "FF${hex}")
    endif()
    set(${c}_HEX "0x${hex}")
  endforeach()
  string(TOUPPER "${S_CORNERS}" corners_in)
  string(TOUPPER "${S_MONITOR}" monitor_in)
  if(corners_in STREQUAL "ROUNDED")
    set(corners Rounded)
  elseif(corners_in STREQUAL "SQUARE")
    set(corners Square)
  else()
    message(FATAL_ERROR "${where}: CORNERS must be ROUNDED or SQUARE, not '${S_CORNERS}'")
  endif()
  if(monitor_in STREQUAL "CURSOR")
    set(monitor Cursor)
  elseif(monitor_in STREQUAL "PRIMARY")
    set(monitor Primary)
  else()
    message(FATAL_ERROR "${where}: MONITOR must be CURSOR or PRIMARY, not '${S_MONITOR}'")
  endif()
  if(S_PROGRESS_BAR)
    set(bar true)
  else()
    set(bar false)
  endif()
  math(EXPR timeout_ms "${S_TIMEOUT_SECONDS} * 1000")
  file(READ "${S_IMAGE}" png HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," png "${png}")
  set(out "${CMAKE_CURRENT_BINARY_DIR}/${target}_startup_screen.cpp")
  file(WRITE "${out}.in" "// Generated by shenora_launcher_startup_screen(${target}). Do not edit.
#include \"shenora/startup_screen.hpp\"
namespace shenora {
namespace {
const unsigned char kPng[] = { ${png} };
}  // namespace
const StartupScreenDescription* embedded_startup_screen() {
    static const StartupScreenDescription d{ ${S_WIDTH}, ${S_HEIGHT}, ${BACKGROUND_HEX}u, kPng, sizeof(kPng), ${bar},
        ${PROGRESS_COLOR_HEX}u, ScreenCorners::${corners}, ScreenMonitor::${monitor}, ${timeout_ms} };
    return &d;
}
}  // namespace shenora
")
  # Rewritten only when it changes, so an unchanged screen is not recompiled on every configure.
  configure_file("${out}.in" "${out}" COPYONLY)
  # The bytes are taken at CONFIGURE time: a changed PNG must re-run CMake, or the build ships the last one.
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${S_IMAGE}")
  target_sources(${target} PRIVATE "${out}")
  target_compile_definitions(${target} PRIVATE SHENORA_STARTUP_SCREEN=1)
endfunction()
